name = "jupiter-proxy" # 你Worker的名称，可以按喜好修改（只能使用小写字母、数字和连字符）
main = "index.js" # 指定入口文件
compatibility_date = "2024-08-01" # 兼容性日期，非常重要

# 以下为触发路由，所有发送到该Worker的请求都会由index.js处理
[[routes]]
pattern = "*jupiter-proxy.*.workers.dev/*" # 匹配你的Worker域名
custom_domain = false